//                                                    

#include <iostream>
#include <math.h>

using namespace std;

void inclusion (double e, double v)
{
    double a = 0;
    double b = max(v, 1.0);
    double x = (a + b)/2;
    if (v == 0)
    {
        cout << "Inclusion square root of "<<v << " is 0" <<endl;
    }
    else if (fabs(b * b - v) <=e)
    {
        cout << "Inclusion square root of "<< v << " is " << b <<endl;
    }
    else
    {
        while (!(fabs(x * x - v)<= e))
        {
            if (x * x < v)
                a = x;
            else
                b = x;
            x = (a + b)/2;
            cout << a << "\t" << b << "\t" << x <<endl;
        }
        cout << "Inclusion square root of "<<v <<" is " << x << " for epsilon " << e <<endl;
    }
}

void newton_raphson (double v, double e)
{
    double x_i = max(1.0,v);
    int i=0;
    while(fabs(x_i*x_i-v)>e)
    {
        i++;
        x_i=(x_i-(x_i*x_i-v))/(2.0*x_i);
        cout << i << "\t" << x_i <<endl;

    }
    if (x_i<0)
        x_i=x_i*-1;
    cout << "Newton_raphson square root of "<< v << " is " << x_i << " for epsilon e" << endl;
}

int main()
{
    inclusion(0.1, 0.0); //      
    //                                           
    inclusion(0.1, 1.0); //      
    //                                           
    inclusion(0.1, 0.5); //          
    //                 
    inclusion(0.1, 9.0); //                         
    //                  
    inclusion(0.1, 63.0); //             
    //                  

    newton_raphson(0.0, 0.1);
    //                 
    newton_raphson(1.0, 0.1);
    //                 
    newton_raphson(0.5, 0.1);
    //                                                               
    newton_raphson(9.0, 0.1);
    //                                                               
    newton_raphson(63.0, 0.1);
    //                                                               
}

/*    

                               
                               
                    
                                                    
                    
                     
                      
                       
                       
                       
                       
                                                     
                     
                     
                       
                       
                       
                       
                       
                       
                       
                                                      
         
                                                  
                                                  
            
             
                   
                
               
                
               
                
               
                 
                
              
                
               
                 
                
                
                
               
                 
               
                
                
                
               
                
              
                 
                 
                
                                                           
            
                
               
                 
                
               
               
                
               
                
                
                
                
               
                
               
                
                
                 
               
                
              
                
               
                
               
                
              
               
               
                
              
                
               
                 
                
               
               
               
                 
                
               
               
               
                 
                
               
                
                
                
               
                
                 
               
                
               
                
               
                 
                
               
                
               
                
               
               
                
               
                
               
                 
                
               
                
                
               
                
                
                 
               
                
               
                
               
                
                
                
               
               
                
                
                
                 
                
               
                
                
                
                
               
                
                
               
                
               
               
               
               
               
               
                
                
                
                 
                
               
                
                
               
                
               
               
               
                 
                
               
               
               
                
               
                
                 
                
               
                
               
                
                
                  
               
               
                
               
                
                
               
                
               
               
                
               
                
               
                
                 
                
               
                
                
                 
               
               
                 
                
               
               
               
                
               
                
               
               
               
                
               
                
                
                 
                
               
                
               
               
               
                
               
                
               
                
                
               
                
                
                 
               
               
               
                
               
                
               
               
               
               
               
                
               
               
               
                 
                
               
               
                
               
                 
                
               
               
                
               
                 
                
               
               
               
               
               
               
               
               
                
               
                
               
                
                 
                
               
                
              
                
               
                
                
                
              
                
                
                
               
                
                 
                
               
               
               
                
               
                
                
                
               
                
                
               
                
                  
                
               
                
               
                
                
                
               
                
                 
                
               
                
               
                
               
                
               
                
                 
                
               
                
                
                
                
               
                
                 
                
               
                
               
                
               
                
              
                
               
                
                
                
               
                
                 
               
                
               
                
               
                
                
               
                
               
               
                
               
                
                
                 
                
               
                
               
                 
                
               
               
                 
               
              
                 
                
              
                
                
               
                
                
               
                
                
               
                
                
                 
                
               
                 
               
                
               
                
               
                
                
               
                
                
              
                
               
               
               
               
                
               
               
               
                
               
               
                
               
               
               
                 
                
               
               
               
               
               
              
                                                       
             
               
                
                
                
                
                
               
               
               
                
               
                
               
               
               
                 
               
               
                
               
               
                 
                
               
                
               
               
                 
                
               
                
                
              
               
               
                
                
                
               
               
              
               
               
                
               
               
               
               
                
                
                
               
               
              
                
               
               
               
               
                
                
                
               
                
               
                
               
                
                 
                
               
                
                
                
               
               
               
               
              
               
                
              
               
               
                
                
                 
                
               
               
               
               
               
               
                 
                
               
                
               
               
               
               
               
               
               
                 
                
               
                
               
              
                 
                
               
                
               
                
                
               
                 
                
               
                
               
              
               
               
               
               
                
                
                 
                
               
               
               
               
               
                
               
                
               
               
                
               
               
                
                 
                
               
                
                
                
              
               
              
               
              
               
                
                
               
                
               
                
              
               
               
                
               
                
                
               
              
               
                
                
               
               
               
                
             
                
               
                
               
               
                
                
               
               
                
               
                
               
                
               
               
                
                
                
                
                
                
                
                
               
               
                
                
                
               
               
                
               
               
               
               
               
                
                
               
                
               
                
                
              
               
                
                
                
                
                
                 
                
               
                
                
               
                
               
                  
                
               
                
               
                
               
                
               
               
               
                
                
               
               
                
                 
                
               
                
               
               
                
                 
                
               
                
               
               
                
               
               
               
                
                
               
                
                
               
               
               
               
               
               
               
               
               
                
                
                
               
               
                
               
              
              
                
               
               
               
               
               
                
                 
                
               
               
                
                
               
                
               
                
              
                
               
               
               
               
               
                
                
               
               
                
               
                
               
                 
                
               
                
                 
                
               
                
               
                 
                
               
                
                
               
                
               
                
                
               
                
                
               
                
              
                
               
                
               
                
               
                 
                
               
                
                 
               
               
                
               
                
                
                
               
              
               
                
                
                
                
                
                
               
               
               
               
               
                
               
               
               
                
               
               
               
                
                
               
               
               
                
                 
                
               
                
               
                
               
                
               
                
             
                 
                
               
                
               
                
               
              
                
               
                
              
                
               
                
                
                
               
                
               
               
               
                  
               
               
                
               
                
               
                
                
               
                
               
               
               
                
               
               
               
                
               
             
               
               
                
                
               
               
               
                
               
               
                
                 
                
               
                
               
                
                
                
             
               
                
               
               
                
                
                
               
                
               
                
               
               
               
                
                 
                
               
                
               
                
                
                
               
                
               
                
               
                
               
                
               
              
               
                
                
                
                
              
                
                
               
               
               
                
                
                
                
                
                
                
               
               
                
               
                
                
                
                
                 
                
               
               
               
                
               
               
               
                
               
               
                
                
                
              
                
                
                 
               
              
                
               
               
               
                
                
               
               
               
                
                 
                
               
                
               
               
                
               
               
              
               
               
               
               
                
                
               
               
                
               
              
               
               
               
               
                 
               
                
              
                
               
                
                
               
                
               
                
                
               
                
               
                
                
                
               
               
               
               
               
               
               
                
                
               
               
               
                
                
               
                
                
                
              
              
               
                
               
               
                 
                
              
                
                 
               
                
               
                
               
                
                
               
                
               
                
                
                
               
               
               
                
               
                
               
                
               
               
               
                
                
               
              
               
               
               
                
                
               
                 
                
               
                
               
               
               
               
               
               
               
                
              
               
              
               
                 
                
               
                
               
                
               
            
                
                
                
                
              
                
               
                
               
                
               
               
                 
                
               
                
               
               
               
                
               
               
                
                
                
                
               
               
                
                
               
               
               
               
                
                
                
                
                
                
                
              
                
                
               
               
               
               
               
                
               
               
               
                
                
                
                
                
               
               
               
                
                
               
                
               
               
               
              
              
                  
                
              
                
               
               
               
                
                
                
               
                
               
                 
               
               
                
               
                
                
                
                 
                
               
                
               
               
               
               
               
               
               
                
                
               
                
               
               
               
                
                
                
                
               
               
                 
                
               
               
               
               
               
                
               
               
                
                
               
               
              
               
               
               
                
               
                
               
                
              
                
                
               
               
               
               
                
                
                
                
                
               
               
                
               
               
               
               
                
                
                
               
               
               
                
               
               
               
               
              
                
                
                
                
              
               
               
              
                
               
               
                
                
                
                
              
               
                
                
                
               
               
              
               
             
               
                
                
                
              
                
                
               
               
                
               
                
               
               
               
                
                
                
               
                
                
                
                
              
                
               
               
               
              
                
               
                
               
               
               
                  
               
                
               
                
               
                
               
                
               
                
                
                
                
                
               
                
                
               
                
              
                
              
               
               
                
                
              
               
                 
                
               
                
               
               
                
               
               
               
               
                
                
               
                
                
                 
                
               
               
                
                
               
               
                
                
                
                
                
                
                
                
               
                
               
                
               
               
                
               
               
               
               
               
                   
             
              
               
                
               
                
               
                
               
                
               
                
               
                
                
               
                
               
               
               
               
               
               
               
               
                
                
                
                
              
               
               
               
               
               
                
               
                
                
               
               
               
               
                
               
               
                
                
               
                
                
               
                
               
                
               
               
                
                
               
                
              
                
                
               
               
                
               
                
               
                
               
               
                
                
               
                
               
               
               
                
               
                
               
                
               
              
               
               
               
               
                
                
                
               
               
               
               
                
               
              
               
               
               
                
               
               
               
              
                
               
               
              
              
               
                
                
                
               
               
                
                
                
               
                
                
                
                
                
                 
                
               
                
               
                 
                
               
                
               
               
               
               
                
               
               
               
                
                
                
                
               
               
               
               
                
                
               
               
                
               
                
             
               
               
                
               
                
                
                
               
               
                
               
                
            
               
               
               
               
                
              
               
               
               
               
                
                
               
                
               
                 
               
              
                
                
                
               
                 
                
              
               
                
                
                
              
                
               
                
               
               
               
               
               
               
               
                
                
               
                
                
                
                
                
               
                
               
                
                
               
                
                
              
                
               
                
               
                
               
                
              
                
                
                
                
               
              
                
               
               
               
               
                 
                
               
                
               
               
                
                
              
               
                
               
               
               
               
                
                
                
                 
                
               
                
                 
                
               
                
              
               
                 
                
               
                
               
              
               
               
               
                
                
               
                 
               
               
                
               
                
               
                
               
                 
                
               
                
             
                
                
                
               
               
               
                
                
                
               
                
              
                
               
                
                
                
             
               
                
                
                
               
                
               
               
               
               
               
               
               
               
               
                
                
                 
               
                
               
                
               
                
               
               
                
                
               
                
               
               
              
                
                
                
                
                
               
                
               
                
                
                
                
                
               
                
               
               
               
               
               
               
               
                
               
               
               
               
                 
               
               
                
              
              
               
               
                
                
               
              
                
                
                
               
               
               
               
                
              
               
               
               
                
               
               
                  
                
               
                
              
                
               
                
               
               
                
                
               
               
               
                
                
              
                
                
               
               
               
               
               
                
               
               
                
               
               
                 
                
               
                
               
                
                
                
               
               
                
               
               
                
               
              
               
                
               
                
               
                
               
                
               
                
               
                
               
                
                
                
               
                
               
                
              
                
                
                
                
                
               
                
               
                
                
               
              
                
               
               
                
                
                
               
               
              
               
               
                
                 
                
               
                
               
                
               
               
                
                
                
                
                
                
                
                 
                
               
                
               
               
               
                
                 
                
               
                
              
                
              
               
                
               
               
                
               
               
                
               
                
               
                
               
                
               
               
               
               
                 
                
               
                
                
                
               
               
                 
                
               
                
                
                
               
               
                
               
                
               
               
                
                
               
                
               
                
               
                 
                
               
                
               
               
                
                
                
               
               
               
               
                
               
               
               
               
               
               
                
                
                
                
                
               
               
               
               
               
               
                
               
               
               
               
                
               
               
               
               
                
                
                 
                
              
               
               
               
               
               
               
                
               
                
                
                
                
                
                
               
               
               
                
                  
                
               
                
               
                
               
                
                
                
                
               
              
                
               
               
               
               
                
                 
                
               
                
               
               
               
               
                
                
               
                
               
                
                 
               
                
               
                
               
                
              
                
                
               
               
                
               
                
               
                
                
                
                
               
               
               
               
               
               
               
               
               
                
                
               
               
                
                
                
                 
                
               
                
               
                
                
               
                 
                
               
                
               
              
               
               
               
                 
                
               
                
               
                
               
               
               
                
               
                
               
                
               
               
               
                
                
                
              
                
               
               
               
                
                
               
               
               
              
              
                
              
               
               
               
               
               
                
                
                
              
                
               
                
               
                
               
                
               
               
               
                 
                
               
               
               
                
               
               
               
               
                
                
               
                 
                
              
                
                
                
              
               
                
                
              
               
                
                
                 
                
               
                
                
                
               
                
               
                
                
                 
                
               
                
               
               
                
                
                
                
               
               
                
               
               
                 
                
               
                
                 
                
               
                
                
                
                 
                
               
                
               
               
               
               
                
               
               
               
               
               
                
                
               
                
                
                
                
               
                
                
               
               
                
                 
               
               
                
                
                
                 
                
               
                
               
               
                
               
               
               
               
                
                
                
               
               
               
               
               
               
                
                
               
               
                
                
                
                
               
                
               
                
               
                
               
               
              
               
               
               
               
                
               
               
                
               
               
               
               
                
               
               
                 
                
               
                
                
                
               
                
               
                
               
                
                
                
               
                
               
                
                
               
                
                
              
               
              
                
                
               
                
               
                
               
                
               
               
               
                 
                
               
                
               
               
                
                
                
              
               
                
               
                
               
                
                
               
               
                
               
               
               
               
               
                
                 
                
               
                
               
               
                 
                
               
                
               
              
               
               
               
               
                
                
               
                
                
               
               
                
               
              
               
               
               
                
                
               
                 
                
               
                
               
               
               
               
                
               
                
               
               
               
                
               
               
               
                 
               
               
                
                
                
                
               
                
               
               
               
               
              
                
                
               
                
               
                
              
               
               
                
                
                
               
               
               
                
                
               
               
               
                
                
               
                
                
             
               
                
              
               
                
                
                
                
                 
                
               
                
               
                
                
               
               
              
               
               
               
                
               
               
                
                
               
               
               
                 
                
               
                
               
               
             
               
               
               
                
               
                
               
                
                
               
               
                
                
               
               
               
               
                 
                
               
                
               
               
                
               
                
              
                
                
                
               
                
                
              
                
               
                
               
                
               
               
                
                
               
              
                
                
                
               
                
               
               
               
                
                
               
                
               
                
                
                
                
               
               
              
                
                
                
              
               
               
                
                
                
                
               
               
               
               
               
               
                
               
               
               
               
               
               
                
               
                
               
                
               
                
                
                
                 
                
               
               
               
               
               
                
               
               
                
               
              
               
                
               
               
                
               
                
               
               
               
                
                
                
                
                
               
              
                  
                
               
                
               
                
               
                
                
               
               
               
               
               
                
                
               
                
              
                
                
               
               
             
               
               
               
              
                
               
               
              
               
                
                
               
               
               
                 
                
              
                
               
                
               
                
               
                
               
                 
                
               
                
               
               
               
                
               
                
               
                
               
               
                
               
              
               
               
                
                
               
               
               
               
                
                
               
               
               
               
               
               
                
                
                
               
                
               
                
               
                
                
                
               
                  
             
              
              
                
               
               
               
                
               
                
               
                
               
               
                
                
                
               
               
                
               
               
                
                
               
                
                
               
               
               
               
                
                
                
               
               
               
               
                
                
                
                
               
               
               
                
                
                
                
               
                 
                
               
                
              
                
              
               
               
               
               
                
               
               
               
                
                
               
                
               
                
               
                
               
               
             
                
                
               
                
                
                
                 
                
              
                
               
               
               
               
                
                
               
               
               
               
               
              
               
               
                
               
               
                
               
                
               
               
               
                
               
               
                
               
                
               
               
               
                  
               
               
                
               
                
               
                
                
                
               
                
               
                
               
                
               
                
                
                
               
              
               
               
               
               
                
                
               
               
               
               
               
               
               
              
                
               
               
               
                
                
                
                
                 
                
               
               
               
               
                
               
                
               
                
                
                
               
                 
                
               
                
               
                
                
                
                
               
               
               
               
                
                 
                
               
                
                 
                
               
                
                
                
               
               
               
               
               
               
                 
               
               
                
               
                
                
               
                
               
                
                
               
                
                
              
               
               
              
                
                
               
                
               
                
               
                
               
               
                
               
                
               
               
               
                
               
                
               
                
                
                 
               
                
               
                
               
                
              
                
                
                
                
                
               
                
              
                
                
                
                
                
               
                
               
               
               
               
                
               
                
               
                
               
               
                
               
               
               
                
                
               
               
               
               
               
               
                
                
                
               
               
               
              
                
                
                
               
               
               
                
                
                
                
               
                 
                
               
                
               
               
               
             
              
               
                
                
                
                 
               
               
                
               
               
               
               
               
                
                
               
               
               
               
                
               
               
                
                
               
               
               
               
               
                
               
               
                
               
              
                
                
                
                
              
               
                 
                
               
                
                
                
               
               
               
                
                
                
              
              
               
               
                
               
                
               
                
                
               
                 
                
               
                
               
                
               
               
                
                
               
               
                
               
               
               
               
               
                
                
             
                 
                
               
                
               
               
                 
                
               
                
               
              
               
               
               
               
               
                
               
                
                
                
                
                
                
                 
                
               
                
               
                
                
                 
                
               
                
                 
                
               
                
                
                
               
                
                
                
                
                
                
                 
               
               
                
              
                
                
                
                
                
                 
                
               
                
               
               
               
                
                 
                
              
               
                
                
               
               
                
               
               
                
                
               
              
               
               
               
                
               
              
                
                
               
               
                
                
               
               
               
              
                
               
             
               
                
                
                
               
                
               
               
                
               
               
                
                 
                
               
                
               
                
               
                
               
                
               
               
               
                
                
                 
                
               
               
               
                
                
                
                
                
                
               
               
               
               
              
               
                 
                
               
                
               
                
               
               
                
               
                
               
                
                
                
                
                
              
               
                
                
                
                
               
              
               
                 
               
                
               
                
               
                
               
                
               
                
               
               
                
               
               
               
                 
                
               
                
               
                
                
               
               
               
                
                
                
                
                
               
              
               
               
              
                
               
                
               
               
                
                
               
              
                
                
               
               
              
               
               
                 
                
               
                
             
               
                
                
                
                
                
               
               
               
               
               
               
                
                
               
                
               
                
                
                
                
               
               
               
                
               
               
                
               
                
               
               
               
                
               
               
               
               
                
               
               
               
               
               
               
               
                
                
               
               
                
                
                
               
                
               
               
               
               
               
               
               
                
               
               
               
               
               
               
                 
                
               
                
               
               
               
               
               
                
                
              
               
                
                
              
               
                
                 
               
                
               
                
               
                
               
                
                 
               
                
               
                
               
                
               
               
                
                
              
               
               
               
                 
                
               
                
               
               
                
               
               
               
              
               
                
                
                
                
               
                
               
               
               
                
                
               
                
               
               
               
                
               
               
               
               
                
               
               
               
               
                
                
               
                
               
                
               
                
                
                
                
               
               
                
               
                
                
                
                
               
                
               
                
               
                
               
                
              
                
                
                
               
               
               
                
                
                
               
                  
                
              
                
               
                
               
                
                
                
                
                
                
                
                
               
                 
               
               
                
               
               
               
               
               
               
                
                
             
               
               
               
               
               
               
                
               
               
                
                
                
               
                
               
                
               
               
              
                
                
                
                
              
                
                
                
               
                
               
                
                
                
                
               
               
                
                
               
                 
                
               
                
                 
                
               
                
                 
                
               
                
               
                
               
                
               
               
               
               
                
                
               
               
               
                
               
               
               
                
               
                
               
               
                
               
               
                
                
                 
                
               
               
                
                
               
               
               
                
               
               
                
              
             
               
                
               
               
               
               
               
               
                
                
                
                
                
               
               
               
              
               
               
              
               
               
                
                
               
                
                
              
               
                
                
                
                
               
               
                
               
                
               
               
                
               
               
                
               
               
                
               
                
               
                
                
               
                
               
                
              
               
                
               
               
               
               
               
               
               
               
               
               
                
                
                
               
                
                
                
               
               
               
                
                
               
               
               
               
                
               
               
               
               
              
               
               
               
               
               
                
               
               
                
                
              
                
               
                 
                
              
                
               
               
             
                
                
               
               
               
                 
                
               
                
                 
                
               
                
               
               
                
                
               
                
               
                
                
               
               
               
                
               
               
               
               
               
               
               
                
                  
                
               
                
               
                
              
                 
              
                
               
                
               
                
               
               
                
                
               
                
              
                
               
                
               
               
               
               
               
               
                
                 
                
               
                
               
                
               
               
                
               
                
               
                
                
                
               
                
               
                
                
                
               
               
                
                
               
               
                
               
                
               
                 
                
               
                
               
               
               
               
               
               
               
                
                
              
               
                
                
               
                
               
                
              
                
                
               
                
               
                
               
                  
                
               
                
               
                
               
                
                
               
               
               
               
               
                
                
               
               
               
                
                
               
                
                
                
                
                
               
                
               
               
               
               
               
                
                
               
              
               
                
               
               
               
               
               
               
               
               
                
               
               
               
               
                
                
               
               
               
                
               
                
                
               
                
               
               
                
                
                
              
               
                 
                
               
                
                
                
                
               
                
               
                
                
               
               
                
               
                
               
               
                
               
               
               
               
               
                
               
               
                
                
              
                 
                
               
                
                
               
                
               
                
               
               
               
               
                
               
               
                
                
                
                
                
                
               
                
               
                
                
               
                
                
                
                
               
                 
                
               
                
                 
                
              
                
               
               
               
              
               
               
                
                
                
               
               
               
               
                
                
               
                
               
              
               
                
                
               
                 
                
               
                
               
                
               
               
                 
                
               
                
                 
                
              
                
               
               
               
                 
                
              
                
                
                
                
               
                
               
                 
                
              
                
               
                
               
               
                
               
                
               
                
                
               
                
                
                
                
                
                
                
               
               
                
               
               
               
               
                
               
               
                 
                
               
                
                 
               
               
                
               
                
               
                
               
               
                
              
             
               
               
               
               
                 
                
               
                
               
                
                
                
               
               
               
               
               
               
                
                
               
                
               
                
                
                
                
               
               
               
               
               
               
               
               
                 
                
               
                
               
                
              
               
               
               
               
                
                
               
               
               
               
               
                
                
                
               
                
                
                
              
                
               
               
               
                
                
                
               
                
               
                 
               
               
                
                
                
               
               
                
               
               
                 
                
               
                
               
               
                
                
                
                
                
              
               
               
                 
                
              
                
               
               
                 
               
               
                
                
                
               
                
                
                
                
               
                
                
                
             
                
                
               
                
              
                
                
               
                
                
               
              
               
                
                
                
               
               
               
                
                
              
              
               
               
               
               
              
               
                
                
                
                
                
                
               
                
               
                
                
                
               
               
              
               
               
                
                
                
               
               
               
               
               
                
                
                
                
                
               
                
                
               
               
               
                 
                
               
                
              
                
               
               
            
               
               
               
               
               
                
                
              
               
               
              
                
                
               
                
              
                
                
                
               
                
               
                 
                
               
                
                
                
                
                
               
                
               
                
               
                
                 
                
               
                
               
                 
               
                
               
                
               
                
               
               
                
                
                
                
               
                
               
                
                
                
              
               
                
                 
                
               
                
               
                
                
               
                
               
                
               
               
                
                 
                
              
                
                 
                
               
                
               
               
               
                
                 
                
               
                
                
                
               
                 
               
               
                
              
                
                
                
                 
                
               
                
               
               
               
               
                
                
                
               
               
                
               
               
                
               
               
               
               
                
                
                
                
               
                
               
                
               
               
               
                
                
                
               
               
                
              
                
               
                
                 
               
                
               
                
               
                
               
               
                
                
              
               
                
               
               
               
               
               
               
                
                
               
               
               
               
                
               
                
                
                
                
              
               
                
                
               
             
                
               
              
                
               
               
               
               
                
                 
                
               
                
               
               
                
               
               
               
               
            
                
                
               
                 
                
               
                
               
                
                
                
               
                
                
                
                
                
                
                    
               
              
                
               
                
               
               
               
                
               
                
               
                
               
                
               
               
               
               
                
                
                 
                
               
                
               
                 
                
              
                
               
                
                
               
                
               
                
               
               
                
              
               
                                                         
*/

